"""
AgentState: Shared state schema for the multi-agent workflow.
All agents read from and write to this typed state dictionary.
"""

from typing import TypedDict, Optional


class AgentState(TypedDict):
    """
    Central state passed between all agents via LangGraph channels.

    Fields
    ------
    query : str
        The user's original natural-language question.
    iteration : int
        Current loop count (0 → max_iterations).
    max_iterations : int
        Upper bound on investigative loops (default 5).
    sub_tasks : list[str]
        Concrete sub-tasks produced by the Lead Detective.
    evidence : list[dict]
        Raw retrieval results (may contain duplicates).
    verified_evidence : list[dict]
        Deduplicated, quality-checked evidence from the Verifier.
    confidence_score : float
        Aggregated confidence in [0.0, 1.0], adjusted for diversity.
    contradictions : list[str]
        Conflicting statements detected across evidence segments.
    detective_notes : str
        Internal reasoning log from the Lead Detective.
    retriever_notes : str
        Internal reasoning log from the Retriever Agent.
    verifier_notes : str
        Internal reasoning log from the Verifier Agent.
    scribe_notes : str
        Internal reasoning log from the Scribe Agent.
    report : str
        Final Markdown forensic report generated by the Scribe.
    """

    # User input
    query: str
    video_id: Optional[str]  # filter retrieval to this specific video

    # Orchestration
    iteration: int
    max_iterations: int

    # Evidence pipeline
    sub_tasks: list[str]
    evidence: list[dict]
    verified_evidence: list[dict]

    # Quality metrics
    confidence_score: float
    contradictions: list[str]

    # Agent notes (debugging / logging)
    detective_notes: str
    retriever_notes: str
    verifier_notes: str
    scribe_notes: str

    # Final output
    report: str
